import {chromium,expect} from '@playwright/test';import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});
const id='00000000-0000-4000-8000-000000000001';const user={id,aud:'authenticated',role:'authenticated',email:'fixture@example.com',app_metadata:{},user_metadata:{}};
const token=Buffer.from('{}').toString('base64url')+'.'+Buffer.from(JSON.stringify({sub:id,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url')+'.fixture';
let amount=500,defaultAmount=500,status='active',stale=false;const mutations=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('https://**.supabase.co/**',async route=>{const req=route.request(),url=new URL(req.url()),body=req.postDataJSON();const send=(value,code=200)=>route.fulfill({status:code,contentType:'application/json',body:JSON.stringify(value)});
if(url.pathname==='/auth/v1/recover'){mutations.push('recover');assert.ok(body.code_challenge);return send({});}
if(url.pathname==='/auth/v1/token')return send({access_token:token,refresh_token:'fixture',token_type:'bearer',expires_in:3600,user});
if(url.pathname==='/auth/v1/user'){if(req.method()==='PUT')mutations.push('password');return send(user);}
if(url.pathname==='/auth/v1/logout')return send({});
if(url.pathname.endsWith('/ai-budget-chat'))return send({answer:'Proposed only.',month:body.month,asOf:new Date().toISOString(),facts:{expectedIncome:3000,target:600,plannedSpending:amount,actualSpending:350,unassignedSpending:0,cautiousHeadroom:1900},proposal:{id:'proposal',month:body.month+'-01',expires_at:new Date(Date.now()+600000).toISOString(),actions:[{kind:'monthly_budget',category:'Dining & Coffee',amount:650}],before_values:[{previous_amount:amount}],status:'pending'}});
if(url.pathname.endsWith('/plaid-create-link-token'))return send({code:'NATIVE_LINK_NOT_CONFIGURED',error:'private-provider-detail'},503);
if(url.pathname.endsWith('/plaid-disconnect')){mutations.push('disconnect');status='disconnected';return send({success:true});}
if(url.pathname.includes('/rpc/')){const name=url.pathname.split('/').pop();if(name==='set_month_budget'){mutations.push(name);amount=body.new_amount;}else if(name==='set_default_budget'){mutations.push(name);defaultAmount=body.new_amount;assert.ok(body.effective_date>new Date().toISOString().slice(0,7)+'-01');}else if(name==='decide_coach_proposal'){mutations.push(body.approve?'approve':'reject');if(stale)return send({message:'stale',code:'40001'},409);if(body.approve)amount=650;return send({status:body.approve?'approved':'rejected'});}else assert.ok(['create_month_budget','create_month_income','expected_paychecks_for_month'].includes(name));return send(name==='expected_paychecks_for_month'?[{},{}]:null);}
assert.equal(req.method(),'GET');assert.equal(url.searchParams.get('user_id'),'eq.'+id);const offset=Number(url.searchParams.get('offset')||0);
if(url.pathname.endsWith('/budget_categories'))return send(offset?[]:[{id:'food',name:'Dining & Coffee',monthly_limit:defaultAmount,category_type:'variable'}]);
if(url.pathname.endsWith('/budget_months'))return send([{category_id:'food',budget_amount:amount}]);if(url.pathname.endsWith('/transactions'))return send([]);if(url.pathname.endsWith('/settings'))return send({savings_per_paycheck:300});if(url.pathname.endsWith('/monthly_savings_overrides'))return send(null);if(url.pathname.endsWith('/monthly_savings_summary'))return send({expected_income:3000});if(url.pathname.endsWith('/bank_connections'))return send([{id:'connection',status,institution_name:'Fixture Bank'}]);throw Error(url.pathname);
});
try{
await page.goto(process.env.BUDGET_TEST_URL||'http://localhost:3001');await page.getByPlaceholder('Email address').fill(user.email);await page.getByRole('button',{name:'Forgot password?'}).click();await expect(page.getByText('If an account exists, a recovery link has been sent. Open it on this device.')).toBeVisible();assert.equal(mutations.filter(x=>x==='recover').length,1);
await page.getByPlaceholder('Password').fill('fixture-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:'Budget',exact:true}).click();await page.getByRole('button',{name:/Edit Dining & Coffee budget/}).click();await page.getByLabel(/Edit Dining & Coffee budget/).fill('650');await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('button',{name:/Edit Dining/})).toContainText('$650.00');assert.equal(defaultAmount,500);
await page.getByRole('button',{name:'Change Dining & Coffee default budget'}).click();await page.getByLabel('Change Dining & Coffee default budget').fill('550');await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('button',{name:'Change Dining & Coffee default budget'})).toContainText('$550.00');assert.equal(amount,650);console.log('PASS: forgot-password PKCE request, inline month-only edits, separate future default');
await page.getByRole('button',{name:'Settings',exact:true}).click();
for(const width of [390,1280]){await page.setViewportSize({width,height:844});for(const name of ['Change password','Widget settings','Privacy / Security','App info']){const toggle=page.getByRole('button',{name,exact:true}).first();await expect(toggle).toHaveAttribute('aria-expanded','false');await toggle.click();await expect(toggle).toHaveAttribute('aria-expanded','true');await toggle.press('Enter');await expect(toggle).toHaveAttribute('aria-expanded','false');await toggle.press('Space');await expect(toggle).toHaveAttribute('aria-expanded','true');await toggle.click();await expect(toggle).toHaveAttribute('aria-expanded','false');}assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
await page.setViewportSize({width:390,height:844});await expect(page.getByLabel('New password',{exact:true})).toBeHidden();await expect(page.getByLabel('Dining & Coffee',{exact:true})).toBeHidden();await page.screenshot({path:'/tmp/settings-collapsed.png',fullPage:true});await page.getByRole('button',{name:'Change password',exact:true}).click();await page.getByLabel('New password',{exact:true}).fill('fixture-new-password');await page.getByLabel('Confirm password').fill('mismatch');await page.getByRole('button',{name:'Change password',exact:true}).last().click();await expect(page.getByText('Use at least 12 characters and matching passwords.')).toBeVisible();assert.ok(!mutations.includes('password'));await page.getByLabel('Confirm password').fill('fixture-new-password');await page.getByRole('button',{name:'Change password',exact:true}).last().click();await expect(page.getByText('Password changed.')).toBeVisible();await expect(page.getByRole('heading',{name:'Privacy / Security'})).toBeVisible();await expect(page.getByRole('heading',{name:'App info'})).toBeVisible();await page.getByRole('button',{name:'Widget settings',exact:true}).click();await page.getByLabel('Dining & Coffee',{exact:true}).uncheck();console.log('PASS: all four Settings accordions default closed, click/Enter/Space toggles at desktop/mobile, password validation/change and widget selection');
await page.getByRole('button',{name:'AI Coach',exact:true}).click();const ask=async()=>{await page.getByLabel('Ask about your budget').fill('Set Dining to $650');await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.getByRole('heading',{name:'Review exact changes'})).toBeVisible();};await ask();assert.ok(!mutations.includes('approve'));await page.getByRole('button',{name:'Reject',exact:true}).click();await expect(page.getByText('Rejected. Nothing changed.')).toBeVisible();await ask();stale=true;await page.getByRole('button',{name:'Approve changes'}).click();await expect(page.getByText(/Not applied or unconfirmed/)).toBeVisible();await ask();stale=false;await page.getByRole('button',{name:'Approve changes'}).click();await expect(page.getByText('Approved change applied. Refreshing your budget.')).toBeVisible();console.log('PASS: exact proposal, no automatic writes, reject, stale failure and explicit approval refresh');
await page.getByRole('button',{name:'Accounts',exact:true}).click();await page.getByRole('button',{name:'Disconnect bank'}).click();assert.ok(!mutations.includes('disconnect'));await page.getByRole('button',{name:'Confirm disconnect'}).click();await expect(page.getByText('Disconnected — connect through Plaid again to reconnect')).toBeVisible();await expect(page.getByRole('button',{name:'Sync Transactions'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Connect Bank',exact:true})).toBeVisible();await page.getByRole('button',{name:'Connect Bank',exact:true}).click();await expect(page.getByText(/iPhone bank linking is not configured yet/)).toBeVisible();await expect(page.getByText('private-provider-detail',{exact:true})).toHaveCount(0);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/ios-mobile-settings.png',fullPage:true});await page.getByRole('button',{name:'Sign out'}).click();await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible();assert.deepEqual(errors,[]);console.log('PASS: confirmed disconnect, sync hidden after revoke, reconnect entry, mobile overflow and sign-out');
}finally{await browser.close();}
